### PR TITLE
Update WebviewCookieManagerPlugin.java

### PR DESCRIPTION
**Pull request by jiechic**
fix if cookie is null will throw exception

### CODE REVIEW

**Comment by jiechic** [comment]
#8 for fix null exception

**Comment by fryette** [comment]
LGTM
@amag2511 please check

**Comment by rodruiz** [comment]
Maybe a ternary operator here looks better.

```java
final ArrayList<String> individualCookieStrings = allCookiesString == null ? new ArrayList<>() : new ArrayList<>(Arrays.asList(allCookiesString.split(";")));
```

**Comment by rodruiz** [comment]
You have to update
- [ ] pubspec.yaml
- [ ] CHANGELOG.md

**Comment by fryette** [comment]
@rodruiz Updated to the ternary operator

**Comment by jiechic** [comment]
> @rodruiz Updated to the ternary operator
> New version already available

Two definitions, no errors in the compilation process?

image

**Comment by fryette** [comment]
Oy shit)
will fix, thx @jiechic

**Pull request merged**
